### ISSUE TITLE
Case count on OPSI platform is off

### ISSUE THREAD

**Issue by jlberryhill** [oecd-opsi/opsi#10] opened 2018-11-06 17:23 UTC
The OPSI platform case count says there are 93 cases, but 100 search results. 
![casecount](https://user-images.githubusercontent.com/7728105/48081732-00b48a80-e1f1-11e8-87c8-cb042aca52be.PNG)

**Comment by jlberryhill** [comment] 2018-11-06 17:29
Looks like the map counts are off as well. There are 2 Portugal cases in the Open Gov platform, but map says 6. Perhaps it is counting cases from both platforms? When I click the country, it takes me to the correct 2 cases. 

![casecount](https://user-images.githubusercontent.com/7728105/48082075-e0390000-e1f1-11e8-8efb-d667ffdc622c.PNG)

**Comment by conlaccento** [comment] 2018-11-07 09:43
About the count the problem is with the _reviewed_ status.
This status is public, as the _published_ status, so all posts with _reviewed_ status are also considered when retrieving search results. We didn't work on this aspect, but if you could explain me the purpose of reviewed status maybe we can find a simple solution.

I just fixed the issue about the map.

**Comment by jlberryhill** [comment] 2018-11-07 09:45
Hi @conlaccento -- the "Reviewed" status is for when we review a case but don't think its ready to be published yet. It's essentially all of the cases that we set aside because they don't meet our submission criteria, or they need more information. Reviewed cases should not count towards the count (only published cases).

**Comment by conlaccento** [comment] 2018-11-07 09:47
So can I set the Reviewed status as not public?

**Comment by jlberryhill** [comment] 2018-11-07 10:40
Correct -- cases that are in the "Reviewed" status should not be pubic. This status is meant purely for administrative sorting of non-published cases.

**Comment by conlaccento** [comment] 2018-11-07 13:37
Perfect, fixed now

**Closed as completed** 2018-11-07 17:09 UTC
